### ISSUE TITLE
Feols: Implement method for F / Wald Tests

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#280]
## Context

Implement support for F & Wald Tests. 

A basic implementation can be found [here](https://github.com/s3alfisc/pyfixest/blob/4533dc25e6a7e180a837c8cad93cbe91684cbdd3/pyfixest/feols.py#L637).

## To do: 

- Review the implementation above. 
- Implement unit tests against e.g. the `clubSandwich` R package. 
- Add documentation.

**Comment by Vksingh306** [comment]
I would like to take this up.

**Comment by s3alfisc** [comment]
Super cool @Vksingh306! I will then assign this to you. Let me know if you run into any problems & feel free to open a PR rather earlier than later =)

For implementing tests, you can either use `rpy2` as e.g. in [here](https://github.com/py-econometrics/pyfixest/blob/master/tests/test_vs_fixest.py) or create a static file of results via a package of your choice (`clubSandwich` is just a suggestion because it is a great package) as e.g. the [tests for ritest](https://github.com/py-econometrics/pyfixest/blob/master/tests/test_ritest.py). Those create a static data set via an R script [here](https://github.com/py-econometrics/pyfixest/blob/master/tests/r_test_comparisons.R) which is then loaded into python in the test file.

**Comment by s3alfisc** [comment]
Hi @Vksingh306, are you actively working on this? If not, would you mind if @Jayhyung would give this a try?

**Comment by Vksingh306** [comment]
Hey sorry for the delay. Sure, please feel free to attempt the issue. I may
not be able to get back to this for a few weeks.

Thanks.

**Comment by s3alfisc** [comment]
Hi, closed with #531 =)
