### ISSUE TITLE
Alpha (confidence interval) not used in plotting functions

### ISSUE THREAD

**Issue by juanitorduz** [py-econometrics/pyfixest#400]
The alpha parameter in the plotting functions `iplot` and `coefplot` is not used

https://github.com/s3alfisc/pyfixest/blob/af27baf87f8b2d78f17c11e55be43cb07a480c34/pyfixest/report/visualize.py#L241

See https://github.com/s3alfisc/pyfixest/pull/395#issuecomment-2080184678 for an idea on how to fix this.

**Comment by rafimikail** [comment]
Hi @s3alfisc , i would like to work on this!

**Comment by s3alfisc** [comment]
Awesome, I've assigned this to you @rafimikail! =)

**Comment by s3alfisc** [comment]
Hi @rafimikail, very nice talking to you earlier! As discussed, here's one way to tackle the issue: 

- add a function argument `alpha` to [Feols.tidy()](https://github.com/py-econometrics/pyfixest/blob/9564935b3cb3fcf9912fa842de0da5b01ac68723/pyfixest/estimation/feols_.py#L1453). 
- if alpha is not `None`, re-compute the confidence interval by reimplementing logic in `self.get_inference()`
- update the CI level names in the series
- pass the `alpha` argument to adjust iplot() and coefplot() (e.g. [here](https://github.com/py-econometrics/pyfixest/blob/9564935b3cb3fcf9912fa842de0da5b01ac68723/pyfixest/report/visualize.py#L151) for iplot)
- adjust the CI levels in [_coefplot](https://github.com/py-econometrics/pyfixest/blob/9564935b3cb3fcf9912fa842de0da5b01ac68723/pyfixest/report/visualize.py#L428) (it always states 95%)
- add some API tests [here](https://github.com/py-econometrics/pyfixest/blob/master/tests/test_plots.py) or [here](https://github.com/py-econometrics/pyfixest/blob/master/tests/test_visualize.py)

And that's it! =)

**Comment by rafimikail** [comment]
Hi @s3alfisc , Thanks for wrapping it up, i will give a try!
