### ISSUE TITLE
CRV3 jackknife with feOLS class

### ISSUE THREAD

**Issue by amichuda** [py-econometrics/pyfixest#476]
Looking at the calculation of LOO "clusterjacks" in `feols`, I see this code:

https://github.com/py-econometrics/pyfixest/blob/37bfe0f95268983ee12b13459626826cce0a808e/pyfixest/estimation/feols_.py#L573-L582

which  `X_g` and `Y_g` are filtered to where they `g==cluster_col`, whereas in the associated loop for all other models, it is:

https://github.com/py-econometrics/pyfixest/blob/37bfe0f95268983ee12b13459626826cce0a808e/pyfixest/estimation/feols_.py#L592-L602

so you are filtering OUT each cluster. Is this by design, or a bug?

**Comment by s3alfisc** [comment]
Hi @amichuda, this is indeed a little bit confusing, but I think this is correct, i.e. not a bug 😅 

I.e. in the second code snipped, we loop over `feols()`, leaving one cluster out of each estimation - we run a classical jackknife. 

The first implementation goes back to work by MacKinnon, Nielsen et al. Basically, they use the fact that you can estimate regressions "in batches". 

You can compute the leave-one-cluster out regression estimator as 

$$
\hat{\beta_{-g}} = ( X'X - X_{g}'X_{g} )^{-1} (X'Y - X_{g} Y_{g})
$$

which goes simply back to the fact that 

$$
\hat{\beta} = (\sum_{g=1}^{G} X_{g}' X_{g})^{-1} X_{g} Y_{g}
$$

This has the advantage that you have to compute X'X and X'Y only once, and X_{g}'X_{g} is faster to compute than X_{-g}'X_{-g} as the data set is smaller. 

See equ (9) in MNW: [link ](https://arxiv.org/pdf/2205.03288)
![image](https://github.com/py-econometrics/pyfixest/assets/19531450/3e0282fc-5783-401b-ba75-a6e749a5a359)

**Comment by amichuda** [comment]
Ah okay perfect, thanks for the clarification. Will close!
