### ISSUE TITLE
Implement PanelView function

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#482]
## Context 

It's often useful (and also recommended, see [this tweet](https://x.com/pedrohcgs/status/1798384924409360506)) to study the treatment rollout in DiD settings. 

In the R world, the [panelView](https://github.com/xuyiqing/panelView) package supports functionality to easily inspect treatment rollout in a panel context

## Task 

Enrich the implementation of the `panel_view` function in #481. 

It would be nice to add the following function arguments: 
- `by_timing`, which sorts units by the timing of receiving the treatment 
- `pre_post`
- `leave_gap`
- `collapse_history`

Additionally, the function should throw a warning if there is a missing time variable for a given cohort.

**Comment by s3alfisc** [comment]
Hi @apoorvalal , Rafi (@rafimikail) has signaled his interest to work on this. He'd pick up the work you started in https://github.com/py-econometrics/pyfixest/pull/481. I guess you wouldn't insist on continuing to work on this? 😄 

To get started, have you already taken a look at the [vignette of the PanelView R package ](https://yiqingxu.org/packages/panelview/) @rafimikail? This PR would mostly consist of adding the function arguments listed above as implemented in PanelView to Appoorva's PR and of course any other feature that you particularly like or see value in =) Is there anything you think we should be prioritizing @apoorvalal?

**Comment by apoorvalal** [comment]
ah yes sorry for letting this slide; yes by all means feel free to pick this up @rafimikail.

**Comment by rafimikail** [comment]
Hi @s3alfisc , I've taken a quick glance, but I haven't gone in-depth yet. I'll make sure to dive into the details of the R package soon.

Also thank you @apoorvalal and @s3alfisc for letting me carry on with this and giving me opportunity 😄! Please assign me with this issue @s3alfisc  =)
