### ISSUE TITLE
Allow users to compute the Romano-Wolf Corrected p-values via randomization inference

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#483]
## Context 

The Romano-Wolf correction for multiple testing can compute resampled t-statistics via either the boostrap (in pyfixest, it uses a wild bootstrap) or randomization inference (see the [Stata Journal paper ](https://docs.iza.org/dp12845.pdf) by Clarke et al, page 6). 

## Task 

Add support for running the Romano-Wolf correction via randomization inference by adding a function argument `sampling_method` that defaults to "wild-bootstrap", but that users can choose to also be "ri". 

If users choose to run randomization inference, instead of running the wild bootstrap via the `wildboottest` method, you can simply run `ritest` via the "randomization-t". 
https://github.com/py-econometrics/pyfixest/blob/30e3a11bb91ad0985878eaf2c51e509c9d1c7d28/pyfixest/estimation/multcomp.py#L133

**Comment by Jayhyung** [comment]
I will take this issue. Thanks.

**Comment by s3alfisc** [comment]
Perfect, thank you! 🎉
