### ISSUE TITLE
Infra: Automate Publication of Release Notes on Github and Changelog

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#491]
## Context

Currently, whenever a new version is released, I need to tag a new release on github "by hand" as well as update the [changelog ](https://py-econometrics.github.io/pyfixest/reference/) in the docs. There must be tools / gh actions out there to automate that procedure?

## To do

- Research the best tools.
- Adjust the github action workflow to automatically publish new release notes, and potentially, to automatically update the changelog. 
- Optimally, we would be able to cluster the content of the release notes by "new features", "breaking changes", "maintenance", "documentation", and "infrastructure".

**Comment by sanskriti2005** [comment]
Hello! I would love to work on this. Can I be assigned to it?

**Comment by s3alfisc** [comment]
Yes, of course! I'll assign this to you then. Thank you =)

**Comment by s3alfisc** [comment]
Hi @sanskriti2005 , maybe you can take some inspiration from the pymc-marketing workflows that Juan has listed here: https://github.com/py-econometrics/pyfixest/issues/492#issuecomment-2156021566.

**Comment by sanskriti2005** [comment]
Thank you for assigning this to me!

**Comment by s3alfisc** [comment]
Of course! =) Let me know if you stumble over any problems / if you need any help!

**Comment by s3alfisc** [comment]
> I'd like to thank you again and in advance for being so supportive and helpful!

Oh it's really up to me to thank you! =) This looks very good and the `release-drafter` seems to be the right tool for the job! 

Yes, the changelog is in [readme.qmd](https://github.com/py-econometrics/pyfixest/blob/master/docs/news.qmd).

I have added three new labels"breaking changes", "infrastructure" and "maintenance". So I think you could put these into the wfl and open the PR =)
