### ISSUE TITLE
Infra: Automate PyPi releases

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#492]
Should we include a gh action to automatically release to PyPi once we merge a new version into main? @juanitorduz , how do you handle this in the PyMC world?

**Comment by juanitorduz** [comment]
In pymc-marketing we do the following steps before every release:

- Update the version file (https://github.com/pymc-labs/pymc-marketing/blob/main/pymc_marketing/version.txt)
- Manually create a GitHub release with a new tag (e.g. https://github.com/pymc-labs/pymc-marketing/releases/tag/0.6.0). See also the release notes generator https://github.com/pymc-labs/pymc-marketing/blob/main/.github/release.yml
- Then the CI pushes this new version to PyPi. Here is the GH we use (I did not write it): https://github.com/pymc-labs/pymc-marketing/blob/main/.github/workflows/pypi.yml . I think you can try to copy-paste the relevant pieces :)
