### ISSUE TITLE
Feols, Fepois, Feiv: Implement Option to use different Solver for Normal Equation

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#496]
## Context

Currently, all fit methods solve the OLS normal equation. 

E.g. for OLS, we have https://github.com/py-econometrics/pyfixest/blob/d922bfc8dbd70f4a91e866a4a6e444ab510dd0db/pyfixest/estimation/feols_.py#L310, for IV we have https://github.com/py-econometrics/pyfixest/blob/d922bfc8dbd70f4a91e866a4a6e444ab510dd0db/pyfixest/estimation/feiv_.py#L145, and for Fepois we have https://github.com/py-econometrics/pyfixest/blob/d922bfc8dbd70f4a91e866a4a6e444ab510dd0db/pyfixest/estimation/fepois_.py#L218. 

It would be cool to allow users to specify different solvers, e.g. `np.linalg.lstsq`.

## To do

- Add a function argument `solver` to `Feols`, `Feiv`, `Fepois`, `feols()` and `fepois`. 
- Allow users to choose between `normal` (the current default) and [np.linalg.lstsq](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html)
- Additionally, consider to allow users to provide additional arguments to solvers via function kwargs. 
- Add unit tests to confirm that different solvers lead to identical results. 

@apoorvalal , any other solvers you'd like to see supported?

**Comment by apoorvalal** [comment]
Good idea; I think using a solver that 'adapts' to the structure of the data would be useful. 

Candidates for linear
+ [scipy.sparse.linalg.lsqr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lsqr.html) [default in scikit's `LinearRegression`]
+ [lineax](https://github.com/patrick-kidger/lineax), gains are particularly large in minimum norm interpolant (p>n) settings like [here](https://github.com/apoorvalal/jaxonometrics/blob/master/jax_linear.ipynb)

For poisson
+ [glum's GLM solvers](https://github.com/Quantco/glum/blob/main/src/glum/_solvers.py) have some very tailored solutions [I don't know much about efficient poisson estimation fwiw]

**Comment by s3alfisc** [comment]
Hi @saidamir, I've assigned you to the issue. Thanks for taking a crack at it! =)

**Comment by saidamir** [comment]
Commenting.

**Comment by saidamir** [comment]
Hi @s3alfisc still struggling to set up my local environment. Also is there a requirements.txt file to import all required libraries? Thanks!

**Comment by s3alfisc** [comment]
Hi @saidamir - we use [poetry](https://github.com/python-poetry/poetry) for package management. I should update the contributing.md with details on how to set it up. Will do so later today!

**Comment by saidamir** [comment]
I tried installing the packages locally using poetry, however there was an error in the processor compatibility.

**Comment by s3alfisc** [comment]
Hm, that's strange, can you post the error message?

**Comment by s3alfisc** [comment]
There's no `requirements.txt.` Could you list all the errors you get when trying to install `just` and the R dependencies? Note that they are not strictly needed for development - they're used only for unit tests, which you can also run on github actions when pushing to a fork / opening a PR.

**Comment by saidamir** [comment]
I imported libraries from using the poetry file as the requirements, however when I tried to run a jupyter notebook on my vscode, I had the errors that I didn't have numpy etc. I started imported them, however got the following error. So finally, what I did, is I started from the beginning, created a new folders, new venv and imported the libraries but didn't use the poetry file. So far it is working ok. Here is the error:
ImportError: dlopen(/Users/kamasam/Documents/pyfixest/pythonProject1/venv/lib/python3.11/site-packages/pandas/_libs/pandas_parser.cpython-311-darwin.so, 0x0002): tried: '/Users/kamasam/Documents/pyfixest/pythonProject1/venv/lib/python3.11/site-packages/pandas/_libs/pandas_parser.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), 
'/System/Volumes/Preboot/Cryptexes/OS/Users/kamasam/Documents/pyfixest/pythonProject1/venv/lib/python3.11/site-packages/pandas/_libs/pandas_parser.cpython-311-darwin.so' (no such file), '/Users/kamasam/Documents/pyfixest/pythonProject1/venv/lib/python3.11/site-packages/pandas/_libs/pandas_parser.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by s3alfisc** [comment]
> I imported libraries from using the poetry file as the requirements, however when I tried to run a jupyter notebook on my vscode, I had the errors that I didn't have numpy etc. I started imported them, however got the following error. So finally, what I did, is I started from the beginning, created a new folders, new venv and imported the libraries but didn't use the poetry file. So far it is working ok. Here is the error:

Sounds like a pragmatic solution! Not really sure how to help with your error - my trusted LLM adviser says this: 

> If you are using a Mac with an M1 or M2 chip, you need to ensure that your Python environment is built for arm64. Verify that your Python version is build for the right architecture by running python -c "import platform; print(platform.architecture())". 

You can install all r packages from the justfile by running `just install-r` - I just merged a PR that fixes a typo in the command. And note that if you're using the justfile from a mac, you need to delete the first line which tells just to use the powershell: 

```bash
set shell := ["powershell.exe", "-c"]
```

**Comment by saidamir** [comment]
Hi I just pushed a pr for one class feols. I would like to see if it is accepted and if yes, continue working on other classes and methods on this ticket.
