### ISSUE TITLE
Contributing Documentation does not show full code blocks

### ISSUE THREAD

**Issue by asteves** [py-econometrics/pyfixest#518]
## Context 

Quarto code blocks do not show full code, leading to errors if contributors try to follow documentation instead of the source qmd file. 

For example, the installing R section in the [source file](https://github.com/py-econometrics/pyfixest/blob/master/docs/contributing.qmd) shows 

```{bash}
Rscript -e 'install.packages(c("broom", "clubSandwich", "did2s", "fixest", "wildrwolf"), repos="https://cran.rstudio.com"); install.packages('ritest', repos = c('https://grantmcdermott.r-universe.dev', 'https://cloud.r-project.org'))'
```

but this is rendered on Safari and Firefox browsers at full screen width as:

<img width="827" alt="Screenshot 2024-06-19 at 2 54 55 PM" src="https://github.com/py-econometrics/pyfixest/assets/24926205/637c4f06-5566-466b-acd6-92498fd6d8b9">

## To Do

- Fix quarto rendering to show full code blocks
- Confirm that this issue does not apply to other files.

**Comment by s3alfisc** [comment]
First of all, thanks for reporting! =) Though I cannot reproduce this. On my firefox, there is a slider to see the full content of the chunk - it's just tiny and barely to see: 

![image](https://github.com/py-econometrics/pyfixest/assets/19531450/20208ce5-5c16-4a08-8039-ecb91fb778e7)

**Comment by asteves** [comment]
Yes, you're totally right. Found that as well after reporting.

Perhaps the project might consider taking advantage of the [code copy functionality](https://quarto.org/docs/output-formats/html-code.html#copy-button)? 

If not I could take that on as an add, otherwise this issue can be closed.
