### ISSUE TITLE
F-test in pyfixest

### ISSUE THREAD

**Issue by ARCCer** [py-econometrics/pyfixest#531]
I'm trying to do 2SLS regression with IVs, where in the first stage we need to do an F-test to show whether the IV is a weak IV. However, when I check the functions, where get_Ftest() is not launched/ developed, are there any methods for me to get F-test results in my first-stage regression?

**Comment by Jayhyung** [comment]
Thanks for letting us know. I'm actually working on this and trying to raise a new issue regarding this, as the first stage diagnostic tools are absent in the current package. Stay tuned for our next update!

**Comment by s3alfisc** [comment]
We actually already have an open issue for this #280 and @Vksingh306 has offered to pick it up =)

**Comment by ARCCer** [comment]
yes, that's great. I hope this package can be better to catch up STATA one day and really thanks to all the contributors for the priceless dedication

**Comment by Jayhyung** [comment]
Hi @ARCCer !

I recently updated `wald_test` method in `feols` class, so you should be able to implement F test on OLS regressions(meaning that you can manually do weak IV test by implementing F test on the 1st stage regression). 
I'll be adding 1st stage F statistics as a default attribute to the `feiv` class soon, but if you have any opinion on any other diagonostic tools related with IV regression, please feel free to comment on the issue #543! Thanks!

**Comment by ARCCer** [comment]
Great thanks for the contribution. While the document notes that we should not directly instantiate Feiv(), but Feols(), so I can get the F-test results with the defined function: _F_stat? or need other settings?

**Comment by ARCCer** [comment]
well , I check the code and the example. So, I can get the F-test results and the related p-value by below codes: fit.wald_test(R=R, distribution="F")
f_stat = fit._f_statistic
p_stat = fit._p_value

**Comment by s3alfisc** [comment]
Yea, exactly, that's the intended use =)we're also working on automatically computing the F test for the first stage when an IV model is run.

**Comment by ARCCer** [comment]
Yeah, thanks for the response. There are some different tests in IV related methods or 2SLS related issues, such as the Hausman test, over-identification test, I hope we can add these tests to make Pyfixest more comprehensive in IV area

**Comment by Jayhyung** [comment]
Thanks for the comment @ARCCer ! In the current PR, I updated robust F statistics(robust to heteorskedasticity and clusteres) and effective F by Olea and Pflueger, which will be updated soon. I will also develop the tests you suggested as the default setting in my next iteration!
