### ISSUE TITLE
Add note on `wald_test` method to `quickstart` (or even a new notebook)?

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#545]
## Context 

Now that we've merged @Jayhyung's #536 , we should tell our users about the `wald_test` method. 

## Task 

Either add a brief section on Wald tests to the `quickstart.ipynb`, or create a small vignette dedicated to Wald Tests. For `quickstart.ipynb`, smth along these lines should suffice: 

```python
import pyfixest as pf 

data = pf.get_data()
fit = pf.feols("Y ~ X1 + X2", data=data)
R = np.eye(3)
fit.wald_test(R = R, q = 2)

# statistic    14978.532559
# pvalue           0.000000
# dtype: float64
```
In a dedicated nb, we could provide a bit of background on Wald Tests, illustrate different constraints matrices `R`, and document the employed dof corrections.

**Comment by s3alfisc** [comment]
One user who I recall requesting support for Wald Tests at some point was @aeturrell =)

**Comment by Jayhyung** [comment]
I will take this one as I reviewed wald test quite heavily for #536, but it will take some time to do so ;). (I actually just cannot take my eyes off the papers on IV tests.)

**Comment by Jayhyung** [comment]
As suggested in #531, I'm also planning to update Hausman and over-identification test. This is the memo for the record!
