### ISSUE TITLE
Add `solver` argument to `feols()`, `fepois()` APIs

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#550]
## Context

@saidamir has added support for multiple solvers in #513. As a follow up, we should make these options available to users via the `feols()` and `fepois()` API. 

## Task

- Add a "solver" argument to the [feols and fepois APIs](https://github.com/py-econometrics/pyfixest/blob/3ab43973de96e867717170c487ccfbfd8160fe7b/pyfixest/estimation/estimation.py#L13) that allows users to select the solver of their choice. 
- Add integration tests to make sure that the different solvers produce equivalent results in [tests/test_api.py ](https://github.com/py-econometrics/pyfixest/blob/master/tests/test_api.py).

**Comment by saidamir** [comment]
@s3alfisc can you please assign this ticket to me? thanks!

**Comment by saidamir** [comment]
@s3alfisc I see that the solver was added from feols to feiv and fepois classes already, so I don't have to do anything there. However, I need to update the test_api.py file to make sure that different solvers are tested. I am struggling with the environment and github sync right now, trying to figure out how to tackle the issues I have on my machine.

**Comment by s3alfisc** [comment]
Hi, I think there's a slight misunderstanding - the task would be to add a `solver` argument to the user-facing `feols` and `fepois` functions, not to the `Feols` and `Fepois` classes (which is what you implemented in the last PR). I.e. to add solver arguments to the functions defined [here](https://github.com/py-econometrics/pyfixest/blob/3ab43973de96e867717170c487ccfbfd8160fe7b/pyfixest/estimation/estimation.py#L13) =)

**Comment by saidamir** [comment]
Got it. I am a bit under the water with job interviews and home takes, hopefully can contribute sooner the better. Lmk if it is urgent.

**Comment by s3alfisc** [comment]
No worries, not urgent at all =)
