### ISSUE TITLE
Add benchmarks against `linearmodels` and `fastreg`

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#558]
## Context

It would be great to add benchmarks against the following two python packages: 

- [linearmodels](https://github.com/bashtage/linearmodels)
- [fastreg](https://github.com/iamlemec/fastreg)

@apoorvalal has benchmarks against `fastreg` [here](https://github.com/apoorvalal/fastreg/blob/master/benchmark.ipynb), showing equal performance to `pyfixest`. 

## To Do

- Adjust the [pyfixest benchmarks ](https://github.com/py-econometrics/pyfixest/blob/master/benchmarks/run_benchmarks.ipynb) by including benchmarks for `linearmodels` and `fastreg`. For `linearmodels`, add benchmarks for OLS, for `fastreg` for OLS and Poisson (linearmodels does not support Poisson afaik). 
- Update the benchmark figures by adjusting and running the [visualize_benchmarks.ipynb](https://github.com/py-econometrics/pyfixest/blob/master/benchmarks/visualise_benchmarks.ipynb) notebook.

**Comment by s3alfisc** [comment]
@rafimikail would you be interested in picking this up?

**Comment by s3alfisc** [comment]
Yes, exactly! Maybe best to start with one of the two packages and divide this into two PRs?

**Comment by rafimikail** [comment]
Certainly @s3alfisc , you can allocate this to me 👍

**Comment by rafimikail** [comment]
Hi @s3alfisc , wanted to confirm, to run_benchmarks.ipynb, i think i need to retrieve some data first that will be used in the notebook, do i need to run data_generation.r first before running the notebook or i could just get it from https://github.com/lrberge/fixest/tree/master/_BENCHMARK?

Thanks!

**Comment by s3alfisc** [comment]
Oh I completely overlooked this - you would have to run the data generation r script first. I can also do so quickly and send you the data as a csv?

**Comment by rafimikail** [comment]
Hey @s3alfisc , i tried to run the data generation r file but experiencing an error, need to find out why

But if you have the data/csv already, that would be helpful

Thanks

**Comment by s3alfisc** [comment]
Will send it in a moment :)

**Comment by marcandre259** [comment]
I have been looking into running the benchmark with linearmodels. It's PanelOLS function, which does the efficient treatment of fixed-effects, only fits into the benchmark scenario with 2 fixed effects (dum1 + dum2).

- It turns out its PanelOLS function supports at most 2 fixed effects ([reference](https://bashtage.github.io/linearmodels/panel/panel/linearmodels.panel.model.PanelOLS.html)).

- Another issue is that the provided indices must be unique, so you cannot have a single fixed effect with values 1, 1, 2, 2 for example.

**Comment by s3alfisc** [comment]
Hi @marcandre259 , super cool that you're looking at this! As far as I understand it, linearmodels has an [AbsorbingOLS ](https://bashtage.github.io/linearmodels/iv/absorbing/linearmodels.iv.absorbing.AbsorbingLS.html#linearmodels.iv.absorbing.AbsorbingLS) function that runs pyhdfe under the hood, which should allow for multiple fixed effects and non-panel data.
