### ISSUE TITLE
installing via pip broken by stargazer

### ISSUE THREAD

**Issue by apoorvalal** [py-econometrics/pyfixest#565]
since stargazer is only listed as a dev dependency but is already used extensively in the package, installing from the repo produces this undesirable behaviour (`pip install git+<url>` installed in a fresh virtualenv)

![image](https://github.com/user-attachments/assets/b6b507b1-c8d8-4088-81fe-97d2a0e345e0)

proposals (mainly so that this error doesn't persist into next release on pypi)
- make (`py-econometrics/stargazer` a default dependency)
- drop it entirely
- merge the existing PR against the main `stargazer` repo

**Comment by s3alfisc** [comment]
Yes, thanks for the pointer Apoorva! We're still [debating ](https://github.com/StatsReporting/stargazer/pull/105) how to best integrate `stargazer` and `pyfixest`, and I think that at least for the next pypi release, it looks like it's swinging in the direction to both drop the `stargazer` dependency & delete the `pf.Stargazer` method from pyfixest's code base.

**Comment by apoorvalal** [comment]
Yeah I think building something minimal and reasonable internally and exposing it via `etable` makes a lot more sense to me tbh; I think `Stargazer` packages end up in the same place :upside_down_face:.

**Comment by s3alfisc** [comment]
Yup, maybe that's the best approach - to not directly depend on the `stargazer` package, to have a nice internal `etable()` function that does the most important things well (and is maybe a little prettier than the current solution), and additionally to make sure that `stargazer` supports `pyfixest` for users who want a lot of customization?

**Comment by apoorvalal** [comment]
Yeah that makes sense; `etable` with reasonable aesthetics is the most a general regression package should promise to deliver IMO. Table customization is a rabbit-hole and promises to become scope-creep for this package. For sufficiently custom tables, there's no better alternative than to pipe numbers directly into text with fstrings `f""" {coef} """` anyway (that's my preferred solution, but probably not the most beginner friendly :laughing: )
