### ISSUE TITLE
Small bugs in `pf.etable()` regarding fixed effects information

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#593]
When the first estimated model contains a fixed effect, but the second does not, the fixed effect column will render `nan` instead of `-`. 

Example: 

```python
import pyfixest as pf

data = pf.get_data()
fit1 = pf.feols("Y ~ X1 | f1", data = data)
fit2 = pf.feols("Y ~ X1", data = data)

pf.etable([fit1, fit2])
```
![image](https://github.com/user-attachments/assets/7e8b93a1-8365-482b-ba04-f530accc2e70)

Then there is yet another bug! 

Printing the models in **opposite order**, i.e. 

```python
pf.etable([fit2, fit1])
```
all columns below the estimated parameters are not sorted appropriately: 
![image](https://github.com/user-attachments/assets/3e33e065-3b4f-4179-b73b-407bbc6765ac)

fyi @dsliwka (I think all of this might have been around for a while already).

**Comment by s3alfisc** [comment]
This does **not** happen when both models have fixed effects: 

```python
import pyfixest as pf

data = pf.get_data()
fit1 = pf.feols("Y ~ X1 | f1", data = data)
fit2 = pf.feols("Y ~ X1 | f2", data = data)

pf.etable([fit1, fit2])
```

![image](https://github.com/user-attachments/assets/861d535e-9c63-4c4c-abf5-ea0bf6e0feed)

**Comment by s3alfisc** [comment]
Alberto, who has reported the bug, has already suggested a quick fix =)

**Comment by dsliwka** [comment]
@s3alfisc: Has the fix solved both issues? Otherwise I of course will have a look. Sorry!

**Comment by s3alfisc** [comment]
Hi Dirk, not your fault and I have a fix. No need for you to take a look. Just tagged you as an fyi =)
