### ISSUE TITLE
Bring back extended tests

### ISSUE THREAD

**Issue by s3alfisc** [py-econometrics/pyfixest#610]
A while back, I unfortunately asked pytest to skip quite a lot of tests in the tests in [test_vs_fixest.py](https://github.com/py-econometrics/pyfixest/blob/master/tests/test_vs_fixest.py). 

We should bring back those tests & add tests for the `predict()` and `resid()` methods (beyond tests already implemented in [test_predict_resid_fixef.py](https://github.com/py-econometrics/pyfixest/blob/master/tests/test_predict_resid_fixef.py)).

**Comment by juanitorduz** [comment]
For bringing the tests bac: Is this a matter of simply passing the `extended` marker on the CI tests?

**Comment by s3alfisc** [comment]
It should all be fixed with this PR https://github.com/py-econometrics/pyfixest/pull/603 - basically consists of getting rid of a lot of poorly chosen `skip` statements

**Comment by juanitorduz** [comment]
ah ok! 👍
