### ISSUE TITLE
The .get_ functions do not appear to return anything

### ISSUE THREAD

**Issue by rlustermans** [py-econometrics/pyfixest#616]
While working with the model object, I noticed that none of the get_ functions are returning any values. For example, model.get_nobs() and model.get_fit(). Is anyone else experiencing this issue, or is it just me?

**Comment by s3alfisc** [comment]
Hi @rlustermans, I admit that the `.get_` methods are poorly named - they are currently only meant for internal use and in consequence, all of them only assign attributes but don't return anything. See here for the [get_nobs()](https://github.com/py-econometrics/pyfixest/blob/22bc38088baecf99c832805dee236d8064ae97f0/pyfixest/estimation/feols_.py#L1506) method. You can obtain the number of observations by calling `fit.nobs()`, coefficients by calling `fit.coef()`, a tidy data frame by calling `fit.tidy()` etc.
