### ISSUE TITLE
Request for dtable enhancement: label ordering

### ISSUE THREAD

**Issue by escherpf** [py-econometrics/pyfixest#647]
In dtable, the ordering of row and column labels resulting from the use of byrow and bycol is currently alphabetical, and does not, as far as I can tell, appear to be something the user can modify. Would it be possible to allow the user to customize the ordering of these labels, akin to the model_heads option in etable?

**Comment by s3alfisc** [comment]
Hi @escherpf, this should certainly be possible! What do you think @dsliwka?

**Comment by dsliwka** [comment]
Hi @escherpf (& @s3alfisc) - that is of course a sensible request. 

I just checked and realized that you can achieve this by using ordered categoricals for the characteristics displayed in rows or columns. In the example in the table layout document for instance just add the following lines before calling dtable:

data["country"] = pd.Categorical(data["country"], categories=["US", "EU"], ordered=True)
data["occupation"] = pd.Categorical(data["occupation"], categories=["White collar", "Blue collar"], ordered=True)

(and adapt the order in the categories list according to your preferences). I will also add this to the documentation.
