### ISSUE TITLE
Randomization inference, "ri" sampling_method in rwolf, gives too tight a sample of null t-statistics

### ISSUE THREAD

**Issue by marcandre259** [py-econometrics/pyfixest#717]
Possible issue I noticed while working on #698. 

The behavior was initially noticed when comparing "wild-bootstrap" to the "ri" sample_method p-values when the parameter of interest has no association with the outcome. 

With the tight null t-distribution, the resulting p-value is too small. 

To reproduce:

```python
import pyfixest as pf
import numpy as np

import matplotlib.pyplot as plt

# Get data and randomize
data = pf.get_data()

np.random.default_rng(232)
data["X1"] = np.random.choice(data["X1"], size=data.shape[0], replace=False)

fit = pf.feols("Y ~ X1", data=data)

fit.summary()
```

Estimation:  OLS
Dep. var.: Y, Fixed effects: 0
Inference:  iid
Observations:  998

| Coefficient   |   Estimate |   Std. Error |   t value |   Pr(>|t|) |   2.5% |   97.5% |
|:--------------|-----------:|-------------:|----------:|-----------:|-------:|--------:|
| Intercept     |     -0.160 |        0.119 |    -1.344 |      0.179 | -0.394 |   0.074 |
| X1            |      0.033 |        0.090 |     0.367 |      0.714 | -0.144 |   0.211 |
---
RMSE: 2.304 R2: 0.0 

```python
seed = 111
df_wild, df_t_wild = fit.wildboottest(param="X1", reps=9999, return_bootstrapped_t_stats=True, seed=seed)

rng = np.random.default_rng(232)
fit.ritest(resampvar="X1", reps=9999, type="randomization-t", store_ritest_statistics=True, rng=rng)

fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(12, 4))
ax[0].hist(fit._ritest_statistics, label="RI t stats", alpha=0.4);
ax[0].axvline(x=fit._ritest_sample_stat, linestyle="--", label="Observed RI t stats", color="black")
ax[0].legend()
ax[1].hist(df_t_wild, label="Wild t stats", alpha=0.4, color="orange");
ax[1].axvline(df_wild["t value"], label="Observed Wild t stat", color="black", linestyle="--");
ax[1].legend()
```

![comparing_null_t_empirical_distributions](https://github.com/user-attachments/assets/0133afa7-d7ef-4a5b-ad92-f08380791d6b)

**Comment by s3alfisc** [comment]
Yes, this looks wrong! I'll take a look later. Thanks for reporting!

**Comment by s3alfisc** [comment]
At second thought, this might not necessarily be a bug, for two reasons: 

- slightly different nulls: first, the randomization inference estimator tests a "sharp" null hypothesis of no effect for **any individual**, i.e. we test that $H0​:Yi​(1)=Yi​(0)$ for all i, which is slightly different from testing that the average treatment effect is zero (which is what we do when we run inference via the bootstrap). 
- different properties of the tests: it might be that the bootstrap is more conservative (or the ritest being less conservative), leading to different distributions

Will have to think about this more - took a look at the code & it looked mostly fine, though will have to check again. Width of the sampling interval differences looks indeed suspicious.

**Comment by marcandre259** [comment]
Hi @s3alfisc,

Based on testing the sharp hypothesis with randomization inference, I would expect the the boostrap approach to be the less conservative one then. 

I'm quickly peeking in this [paper](https://projecteuclid.org/journals/statistical-science/volume-32/issue-3/A-Paradox-from-Randomization-Based-Causal-Inference/10.1214/16-STS571.pdf) that confirms this with simulations in table 1 (Fischer -> sharp, Neyman -> average afaik). 

Namely, sharp null rejection implies average null rejection. 

As far as progress on #698, I'll get back to including RI for Westfall-Young now that this is open.

**Comment by s3alfisc** [comment]
Looking at your results above - it simply looks to me as if the wild cluster bootstrap simply creates **super wide** CIs vs RI and also analytical standard errors. The RI interval more or less agrees with the analytical: 

![image](https://github.com/user-attachments/assets/0888d5dd-7c92-47ed-9330-bfe4e6988bef)

**Comment by marcandre259** [comment]
Hmm I guess I wonder how those t stats are computed, usually the standard error would be about 1? , and do you notice anything weird when running tests when the null hypothesis of no association between x and y is true? 

I was brought into this because I would get a "reasonable" p value on the bootstrap but a p val of about 0 when using the ri on those kind of associations.

**Comment by s3alfisc** [comment]
Here is a check against the ritest and fwildclusterboot r packages - R and Python seem to match quite well!

```{python}
import pyfixest as pf 

data = pf.get_data(N = 100)

fit = pf.feols("Y~X1", data = data)
fit.tidy()
#              Estimate  Std. Error   t value  Pr(>|t|)      2.5%     97.5%
# Coefficient                                                              
# Intercept    0.701510    0.533612  1.314646  0.191761 -0.357700  1.760721
# X1          -0.460607    0.432758 -1.064353  0.289839 -1.319625  0.398411
fit.ritest(resampvar = "X1", reps = 1000)
# H0                                      X1=0
# ri-type                      randomization-c
# Estimate                 -0.4606070841379411
# Pr(>|t|)                            0.308308
# Std. Error (Pr(>|t|))               0.024032
# 2.5% (Pr(>|t|))                     0.268779
# 97.5% (Pr(>|t|))                    0.347838
fit.wildboottest(param = "X1", reps = 999)
# param                             X1
# t value                    -1.079268
# Pr(>|t|)          0.2852852852852853
# bootstrap_type                    11
# inference                         HC
# impose_null                     True

```



```{r}
library(reticulate)
library(fixest)
library(ritest)
library(fwildclusterboot)

data = py$data
fit = feols(Y ~ X1, data = data)
ritest(fit, resampvar = ~X1, reps = 1000)
 #  T(obs)         c         n     p=c/n     SE(p)   CI 2.5%  CI 97.5%  
 # -0.4606       284      1000     0.284   0.02347    0.2454    0.3226  
boottest(fit, param = "X1", B = 999)
# > tidy(r)
#       term   estimate statistic   p.value conf.low conf.high
# 1 1*X1 = 0 -0.4606071 -1.079268 0.3003003       NA        NA
```

**Comment by s3alfisc** [comment]
It seems to me as if there was a bug in the randomization-t implementation: 

```python
fit.ritest(resampvar = "X1", reps = 1000, type = "randomization-c")
# H0                                      X1=0
# ri-type                      randomization-c
# Estimate                 -0.4606070841379411
# Pr(>|t|)                            0.308308
# Std. Error (Pr(>|t|))               0.024032
# 2.5% (Pr(>|t|))                     0.268779
# 97.5% (Pr(>|t|))                    0.347838
fit.ritest(resampvar = "X1", reps = 1000, type = "randomization-t")
# H0                                      X1=0
# ri-type                      randomization-t
# Estimate                 -0.4606070841379411
# Pr(>|t|)                            0.014014
# Std. Error (Pr(>|t|))               0.006117
# 2.5% (Pr(>|t|))                     0.003952
# 97.5% (Pr(>|t|))                    0.024076
```

**Comment by s3alfisc** [comment]
@all-contributors please add @marcandre259 for bug
