### ISSUE TITLE
Unexpected keyword argument 'fml_second_stage' error in v0.26.2

### ISSUE THREAD

**Issue by escherpf** [py-econometrics/pyfixest#735]
After upgrading to version 0.26.2, I get the following error message when running a simple regression using <pf.feols> without any FEs or IVs, that had under previous versions worked fine: 

_Formula.__init__() got an unexpected keyword argument 'fml_second_stage'_ 

When I downgrade to v0.26.1, everything works fine again.  

Is this a known issue? 

Thank you.

Below is the full error message:

> _{
> 	"name": "TypeError",
> 	"message": "Formula.__init__() got an unexpected keyword argument 'fml_second_stage'",
> 	"stack": "---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> File  [Redacted]
> ----> 1 pf.feols('Y ~ X1 + X2 + X3 + X4',data=df_chg_01x)
> 
> File ~\\AppData\\Roaming\\Python\\Python311\\site-packages\\pyfixest\\estimation\\estimation.py:412, in feols(fml, data, vcov, weights, ssc, fixef_rm, fixef_tol, collin_tol, drop_intercept, i_ref1, copy_data, store_data, lean, weights_type, solver, use_compression, reps, seed, split, fsplit)
>     407 fixest._prepare_estimation(
>     408     estimation, fml, vcov, weights, ssc, fixef_rm, drop_intercept
>     409 )
>     411 # demean all models: based on fixed effects x split x missing value combinations
> --> 412 fixest._estimate_all_models(vcov, collin_tol=collin_tol, solver=solver)
>     414 if fixest._is_multiple_estimation:
>     415     return fixest
> 
> File ~\\AppData\\Roaming\\Python\\Python311\\site-packages\\pyfixest\\estimation\\FixestMulti_.py:281, in FixestMulti._estimate_all_models(self, vcov, solver, collin_tol, iwls_maxiter, iwls_tol, separation_check)
>     262 if _method == \"feols\" and not _is_iv:
>     263     FIT = Feols(
>     264         FixestFormula=FixestFormula,
>     265         data=_data,
>    (...)
>     279         sample_split_var=_splitvar,
>     280     )
> --> 281     FIT.prepare_model_matrix()
>     282     FIT.demean()
>     283     FIT.to_array()
> 
> File ~\\AppData\\Roaming\\Python\\Python311\\site-packages\\pyfixest\\estimation\\feols_.py:316, in Feols.prepare_model_matrix(self)
>     314 def prepare_model_matrix(self):
>     315     \"Prepare model matrices for estimation.\"
> --> 316     mm_dict = model_matrix_fixest(
>     317         FixestFormula=self.FixestFormula,
>     318         data=self._data,
>     319         drop_singletons=self._drop_singletons,
>     320         drop_intercept=self._drop_intercept,
>     321         weights=self._weights_name,
>     322     )
>     324     self._Y = mm_dict.get(\"Y\")
>     325     self._Y_untransformed = mm_dict.get(\"Y\").copy()
> 
> File ~\\AppData\\Roaming\\Python\\Python311\\site-packages\\pyfixest\\estimation\\model_matrix_fixest_.py:106, in model_matrix_fixest(FixestFormula, data, drop_singletons, weights, drop_intercept)
>      97 _is_iv = fml_first_stage is not None
>      99 fml_kwargs = {
>     100     \"fml_second_stage\": fml_second_stage,
>     101     **({\"fml_first_stage\": fml_first_stage} if _is_iv else {}),
>     102     **({\"fe\": wrap_factorize(fval)} if fval != \"0\" else {}),
>     103     **({\"weights\": weights} if weights is not None else {}),
>     104 }
> --> 106 FML = Formula(**fml_kwargs)
>     107 mm = FML.get_model_matrix(data, output=\"pandas\", context={\"factorize\": factorize})
>     108 endogvar = Z = weights_df = fe = None
> 
> TypeError: Formula.__init__() got an unexpected keyword argument 'fml_second_stage'"
> }_

**Comment by s3alfisc** [comment]
Hi @escherpf, I haven't seen this before. Could you provide a reproducible example? Thanks for reporting!

**Comment by escherpf** [comment]
I stepped away from this project for a few days, and now I haven't yet been able to reproduce this error, so it's likely some error on my part. I will close this issue, and reopen if I'm eventually able to reproduce. Sorry for jumping the gun on this!

**Comment by s3alfisc** [comment]
Hi, no worries at all and thanks for reporting @escherpf! With bugs, I definitely much prefer false positives over potentially not hearing about real issues! =)
